### ISSUE TITLE
`pip3 install ppinject` ?

### ISSUE THREAD

**Issue by huan** [trein/pydi#3]
According to https://github.com/google/pinject/pull/9#issuecomment-318376040, we have this fork workable for Python 3.x, and I had use it in my project without any problem by pip install directly from this git repo.

If we still can not get any response from the original author(the last activity is FIVE years ago), I'd like to suggest @trein to publish this repo as a new python module on PyPI.

And thank you again for the fix on Python 3.x!

**Comment by huan** [comment]
I feel `pydi` is a great name! 

I had just sent an email to Kurt, who is the author of pinject, and CCed to you.

**Comment by trein** [comment]
Thanks @zixia for all the effort in reviving the original Pinject project. I'm closing this issue as [Pinject](https://github.com/google/pinject/pulls) will be officially maintained.
